title: Michal Šváb
url: http://michal.svab.net
markdown: kramdown
lsi: false
relative_permalinks: false
encoding: utf-8
exclude: ['Gemfile', 'Gemfile.lock']
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter
sass:
  style: :compressed
  sass_dir: assets/css
